### ISSUE TITLE
[BUG] - Outer glow/stroke and shadows dont show up

### ISSUE THREAD

**Issue by MegalordX8** [FiniteSingularity/obs-stroke-glow-shadow#49]
For some reason when I try to set either a shadow, stroke or glow to a source in OBS to the outer position, it just dosent show up at all, no matter what settings I adjust, it dosent show up.

**Comment by FiniteSingularity** [comment]
Hi @MegalordX8-

This is due to how OBS renders sources.  Essentially, it can not render outside of the bounds of the source, and so if you're applying an outer stroke/glow/shadow to a source that completely fills its bounds, it will not appear.  However, there is a workaround.  Add a crop/pad filter (it comes with OBS) in the filter list *before* the stroke, glow, or shadow, and give a negative padding value for all sides.  This will extend the bounds of the source, and allow the filter to show.  More details can be found in issue #35 .

I'm actively working on the next SGS release, and will include an auto-bounds-extension option, but for now you'll need to use the crop/pad workaround.

**Comment by MegalordX8** [comment]
I found that by adding a border of empty pixels around the image fixes the issue, thank you for the help

**Comment by FiniteSingularity** [comment]
I'm glad you got it working.  Stay tuned, as the next release (which I'm currently working on) should have a "auto-pad" option which will do this for you.  I'm going to close this, but if you have any ideas for padding/auto padding, please feel free to post in the comments of issue #35
